// <auto-generated />
namespace MvcApplication1.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddPictures : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPictures));
        
        string IMigrationMetadata.Id
        {
            get { return "201211171752360_AddPictures"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
