// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Llprk.Web.UI.Areas.Admin.Controllers
{
    public partial class ThemesController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ThemesController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Edit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UpdateItem()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateItem);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CreateItem()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateItem);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteItem()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteItem);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RenameItem()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RenameItem);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Content()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Content);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RenderTemplate()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RenderTemplate);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ThemesController Actions { get { return MVC.Admin.Themes; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Themes";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Themes";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Edit = "Edit";
            public readonly string UpdateItem = "UpdateItem";
            public readonly string CreateItem = "CreateItem";
            public readonly string DeleteItem = "DeleteItem";
            public readonly string RenameItem = "RenameItem";
            public readonly string Content = "Content";
            public readonly string RenderTemplate = "RenderTemplate";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Edit = "Edit";
            public const string UpdateItem = "UpdateItem";
            public const string CreateItem = "CreateItem";
            public const string DeleteItem = "DeleteItem";
            public const string RenameItem = "RenameItem";
            public const string Content = "Content";
            public const string RenderTemplate = "RenderTemplate";
        }


        static readonly ActionParamsClass_Edit s_params_Edit = new ActionParamsClass_Edit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Edit EditParams { get { return s_params_Edit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Edit
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_UpdateItem s_params_UpdateItem = new ActionParamsClass_UpdateItem();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateItem UpdateItemParams { get { return s_params_UpdateItem; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateItem
        {
            public readonly string id = "id";
            public readonly string type = "type";
            public readonly string theme = "theme";
            public readonly string content = "content";
        }
        static readonly ActionParamsClass_CreateItem s_params_CreateItem = new ActionParamsClass_CreateItem();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateItem CreateItemParams { get { return s_params_CreateItem; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateItem
        {
            public readonly string id = "id";
            public readonly string type = "type";
            public readonly string theme = "theme";
        }
        static readonly ActionParamsClass_DeleteItem s_params_DeleteItem = new ActionParamsClass_DeleteItem();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteItem DeleteItemParams { get { return s_params_DeleteItem; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteItem
        {
            public readonly string id = "id";
            public readonly string type = "type";
            public readonly string theme = "theme";
        }
        static readonly ActionParamsClass_RenameItem s_params_RenameItem = new ActionParamsClass_RenameItem();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RenameItem RenameItemParams { get { return s_params_RenameItem; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RenameItem
        {
            public readonly string id = "id";
            public readonly string type = "type";
            public readonly string theme = "theme";
            public readonly string newName = "newName";
        }
        static readonly ActionParamsClass_Content s_params_Content = new ActionParamsClass_Content();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Content ContentParams { get { return s_params_Content; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Content
        {
            public readonly string id = "id";
            public readonly string type = "type";
            public readonly string theme = "theme";
        }
        static readonly ActionParamsClass_RenderTemplate s_params_RenderTemplate = new ActionParamsClass_RenderTemplate();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RenderTemplate RenderTemplateParams { get { return s_params_RenderTemplate; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RenderTemplate
        {
            public readonly string layout = "layout";
            public readonly string templateHtml = "templateHtml";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Edit = "Edit";
                public readonly string Index = "Index";
            }
            public readonly string Edit = "~/Areas/Admin/Views/Themes/Edit.cshtml";
            public readonly string Index = "~/Areas/Admin/Views/Themes/Index.cshtml";
            static readonly _EditorsClass s_Editors = new _EditorsClass();
            public _EditorsClass Editors { get { return s_Editors; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _EditorsClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string _404 = "_404";
                    public readonly string _Image = "_Image";
                    public readonly string _Text = "_Text";
                    public readonly string _Unsupported = "_Unsupported";
                }
                public readonly string _404 = "~/Areas/Admin/Views/Themes/Editors/_404.cshtml";
                public readonly string _Image = "~/Areas/Admin/Views/Themes/Editors/_Image.cshtml";
                public readonly string _Text = "~/Areas/Admin/Views/Themes/Editors/_Text.cshtml";
                public readonly string _Unsupported = "~/Areas/Admin/Views/Themes/Editors/_Unsupported.cshtml";
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ThemesController : Llprk.Web.UI.Areas.Admin.Controllers.ThemesController
    {
        public T4MVC_ThemesController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Edit(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EditOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void UpdateItemOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id, string type, string theme, string content);

        [NonAction]
        public override System.Web.Mvc.ActionResult UpdateItem(string id, string type, string theme, string content)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateItem);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "type", type);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "theme", theme);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "content", content);
            UpdateItemOverride(callInfo, id, type, theme, content);
            return callInfo;
        }

        [NonAction]
        partial void CreateItemOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id, string type, string theme);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateItem(string id, string type, string theme)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateItem);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "type", type);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "theme", theme);
            CreateItemOverride(callInfo, id, type, theme);
            return callInfo;
        }

        [NonAction]
        partial void DeleteItemOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id, string type, string theme);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteItem(string id, string type, string theme)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteItem);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "type", type);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "theme", theme);
            DeleteItemOverride(callInfo, id, type, theme);
            return callInfo;
        }

        [NonAction]
        partial void RenameItemOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id, string type, string theme, string newName);

        [NonAction]
        public override System.Web.Mvc.ActionResult RenameItem(string id, string type, string theme, string newName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RenameItem);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "type", type);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "theme", theme);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "newName", newName);
            RenameItemOverride(callInfo, id, type, theme, newName);
            return callInfo;
        }

        [NonAction]
        partial void ContentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id, string type, string theme);

        [NonAction]
        public override System.Web.Mvc.ActionResult Content(string id, string type, string theme)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Content);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "type", type);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "theme", theme);
            ContentOverride(callInfo, id, type, theme);
            return callInfo;
        }

        [NonAction]
        partial void RenderTemplateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, DotLiquid.Template layout, string templateHtml);

        [NonAction]
        public override System.Web.Mvc.ActionResult RenderTemplate(DotLiquid.Template layout, string templateHtml)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RenderTemplate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "layout", layout);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "templateHtml", templateHtml);
            RenderTemplateOverride(callInfo, layout, templateHtml);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
